### ISSUE TITLE
Configuration File type is not supported: Clickgen 2.1.6

### ISSUE THREAD

**Issue by yochananmarqos** [ful1e5/Bibata_Cursor#143]
Attempting to build my [`bibata-cursor-theme` ](https://aur.archlinux.org/packages/bibata-cursor-theme)AUR package with `python-clickgen` 2.1.6:

```
[Fail] Error occurred while processing build.toml:
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/clickgen/scripts/ctgen.py", line 157, in process
    cfg = parse_config_file(str(file.resolve()), **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/clickgen/configparser.py", line 187, in parse_config_file
    raise IOError("Configuration File type is not supported")
OSError: Configuration File type is not supported
[Fail] Error occurred while processing build.toml:
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/clickgen/scripts/ctgen.py", line 157, in process
    cfg = parse_config_file(str(file.resolve()), **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/clickgen/configparser.py", line 187, in parse_config_file
    raise IOError("Configuration File type is not supported")
OSError: Configuration File type is not supported
[Fail] Error occurred while processing build.toml:
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/clickgen/scripts/ctgen.py", line 157, in process
    cfg = parse_config_file(str(file.resolve()), **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/clickgen/configparser.py", line 187, in parse_config_file
    raise IOError("Configuration File type is not supported")
OSError: Configuration File type is not supported
[Fail] Error occurred while processing build.toml:
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/clickgen/scripts/ctgen.py", line 157, in process
    cfg = parse_config_file(str(file.resolve()), **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/clickgen/configparser.py", line 187, in parse_config_file
    raise IOError("Configuration File type is not supported")
OSError: Configuration File type is not supported
[Fail] Error occurred while processing build.toml:
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/clickgen/scripts/ctgen.py", line 157, in process
    cfg = parse_config_file(str(file.resolve()), **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/clickgen/configparser.py", line 187, in parse_config_file
    raise IOError("Configuration File type is not supported")
OSError: Configuration File type is not supported
[Fail] Error occurred while processing build.toml:
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/clickgen/scripts/ctgen.py", line 157, in process
    cfg = parse_config_file(str(file.resolve()), **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/clickgen/configparser.py", line 187, in parse_config_file
    raise IOError("Configuration File type is not supported")
OSError: Configuration File type is not supported
```

**Comment by ful1e5** [comment]
@yochananmarqos Could you please share the local PKGBUILD for `python-cickgen` so that I can easily debug the build process?

**Comment by yochananmarqos** [comment]
<details>
<summary>PKGBUILD</summary>

```
pkgname=python-clickgen
_name=${pkgname#python-}
pkgver=2.1.6
pkgrel=1
pkgdesc="X11 & Windows cursor building API"
arch=('any')
url="https://github.com/ful1e5/clickgen"
license=('MIT')
depends=('python-attrs' 'python-numpy' 'python-pillow' 'python-toml' 'python-yaml')
makedepends=('python-build' 'python-installer' 'python-setuptools' 'python-wheel')
source=("$_name-$pkgver.tar.gz::$url/archive/refs/tags/v$pkgver.tar.gz")
sha256sums=('5b9d049b6c47989ad650b5ba7fcd34cb9219d12d0385145a11a6767101f1168a')

build() {
  cd "$_name-$pkgver"
  python -m build --wheel --no-isolation
}

package() {
  cd "$_name-$pkgver"
  python -m installer --destdir="$pkgdir" dist/*.whl

  install -Dm644 LICENSE -t "$pkgdir/usr/share/licenses/$pkgname/"
}
```

</details>

**Comment by ful1e5** [comment]
@yochananmarqos I tested building Bibata using the `PKGBUILD` you provided. I believe the issue may be on your end, or it seems that the `build.toml` you are using for building Bibata either doesn't exist or is not parsing correctly, as I can observe from your logs.

https://github.com/ful1e5/Bibata_Cursor/assets/24286590/0999048b-4403-484e-8661-b2d405f5ad2c

**Comment by yochananmarqos** [comment]
The video you posted is of building `python-clickgen`, not `bibata-cursor-theme`. Did you use the AUR [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=bibata-cursor-theme)?

If there's something wrong on my end, then why does it build fine with `python-clickgen` 2.1.3?


Tip: Use the `-s` flag with `makepkg` to install dependencies. :wink:

**Comment by ful1e5** [comment]
Patched in https://github.com/ful1e5/clickgen/commit/889f9794dc2affd4f778acf8a7792a35a6a29d6e and will be available in the next `clickgen` release.

**Comment by ful1e5** [comment]
@yochananmarqos clickgenhttps://github.com/ful1e5/clickgen/releases/tag/v2.1.7

**Comment by yochananmarqos** [comment]
2.1.7 resolves the issue. :+1:
